### ISSUE TITLE
Improve template design

### ISSUE THREAD

**Issue by vincentdelitz** [corbado/next.js-template-vercel#2]
- [x] Remove "Login" & "Sign up for free" button when the user is already loggedin:
![image](https://github.com/corbado/nextjs-template-vercel/assets/18458907/e305f7a2-1955-4466-8876-a4d189df2c37)

- [x] Also it's confusing that there are 2 "Created at" fields, as it's not obious that they stand for the "created at" date of the email or phone number. Can we please remove one "Created at", so that there's only one "Created" (no "at"). Can we take this information from the API response?
- [x] "user details:" looks a bit like a technical error message. Either change the font type/color/size and make it with capital "U" (User details) or remove it entirely.
- [x] Any chance we can turn the icons white? Or tis this restricted by the component?
![image](https://github.com/corbado/nextjs-template-vercel/assets/18458907/54220df8-7355-4e65-b965-7142136d52ad)
- [x] Modal with the "Passkey Already exists" test, has white font making the modal message non-readable. Please change font color or background:
![image](https://github.com/corbado/nextjs-template-vercel/assets/18458907/03d1f23a-b56b-4946-a98d-59dfd3c61fab)
- [x] On "Session Details" and "Passkey List", there should be something like a uniform header (like we have with the salutation on "Overview"):
![image](https://github.com/corbado/nextjs-template-vercel/assets/18458907/90095b92-f414-4df4-961c-9f0eb426f7b9)
- [x] Change "This is your shortSession" to "The following data is available in your short-term session (represented as JWT):"

**Comment by karunasolanki** [comment]
1. The login/sign-up buttons are not present after logging in
2. I didn’t find SVG’s for these icons, these are part of react package (packages/shared-ui/src/assets) and Abdullah told me that they can’t be changed directly.
3. Other points are covered and updated.:).

**Comment by vincentdelitz** [comment]
- [x] Regarding the SVGs, then following suggestion. Can we make the background around the passkey-list component lighter and then use passkey-list with black font / borders?
- [x] Can you put "Created at" as "Created" (no at) to the bottom and give it the same style as all the other attributes (=> add an icon as well)?
![image](https://github.com/corbado/nextjs-template-vercel/assets/18458907/641e90be-89e3-44aa-a6c3-f6d2795bbd6d)
- [x] The menu looks a bit weird, as the "Sign Out" button looks to prominent IMO. Maybe make it a secondary button / outlined?
- [x] for all the sections (Overview, Session Details, Passkey List), is it somehow possible that the headings start at the same position from the top?
- [x] on mobile, the "Check the code" button is transparent, so taht you can see the background graphics -> please make it non-transparent:
![image](https://github.com/corbado/nextjs-template-vercel/assets/18458907/f771dd3d-d941-44c5-a3b3-ab22caf5de0c)
- [x] Please improve the mobile responsiveness in general (menu, buttons, alignments, etc.)
![image](https://github.com/corbado/nextjs-template-vercel/assets/18458907/43bd975c-7333-43b1-9822-59ce59e2f2fe)

**Comment by vincentdelitz** [comment]
- [x] on the Passkey list page, the heading is not starting on the same position as on the other pages.
- [x] can we move the menu with the four buttons a bit up, as it's currently too much blank space between the bar on the very top and the four buttons: 
![image](https://github.com/corbado/nextjs-template-vercel/assets/18458907/503fecb7-e6fe-417d-b9fa-d885c408e89d)
- [x] On mobile, the texts here should be aligned:
![image](https://github.com/corbado/nextjs-template-vercel/assets/18458907/986dd40a-d9b9-460b-ab25-331b09a50413)

- [x] Please change from "Created at" to "Created" the label

**Comment by karunasolanki** [comment]
@vincentdelitz Can you please check now and let me know:). For the 3rd point, because of the space taken by "Phone number" the text is getting in right side but I have updated that until screen size of iPhone SE (with min 375x667) I believe if smaller size than this, the box will get shifted downwards.

**Comment by vincentdelitz** [comment]
Looks good minor last feedback :)
- [x] remove the copy symbol in "Session Details" if it has not functionality
- [x] On the same page, can we make the tab for the JSON values a bit bigger, meaning that "iss": ... starts more on the right?

**Comment by karunasolanki** [comment]
@vincentdelitz I have updated the design. Can you please check and let me know:)
